#!/bin/sh
zip -d iicaptain-bb www/splashes/ipad-landscape.png
zip -d iicaptain-bb www/splashes/Default-Landscape@2x~ipad.png
zip -d iicaptain-bb www/splashes/Default-Landscape~ipad.png
zip -d iicaptain-bb www/splashes/Default-Portrait@2x~ipad.png
zip -d iicaptain-bb www/splashes/Default-Portrait~ipad.png
zip -d iicaptain-bb www/splashes/Default@2x.png
#zip -d iicaptain-bb www/splashes/Default.png
zip -d iicaptain-bb www/media/img12.jpg
zip -d iicaptain-bb www/media/img13.jpg
zip -d iicaptain-bb www/media/img14.jpg
zip -d iicaptain-bb www/media/img15.jpg
zip -d iicaptain-bb www/media/img16.jpg
zip -d iicaptain-bb www/media/img17.jpg
zip -d iicaptain-bb www/media/img18.jpg
zip -d iicaptain-bb www/media/img19.jpg
zip -d iicaptain-bb www/media/img20.jpg
zip -d iicaptain-bb www/media/img21.jpg
zip -d iicaptain-bb www/media/img22.jpg
zip -d iicaptain-bb www/media/img23.jpg
zip -d iicaptain-bb www/media/img24.jpg
